"""create pipelines and pipeline_versions tables

Revision ID: 0351bb59d9e3
Revises: ef906c1af563
Create Date: 2026-05-12 09:44:36.437842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0351bb59d9e3'
down_revision: Union[str, None] = 'ef906c1af563'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_versions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('pipeline_id', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('plan_json', sa.Text(), nullable=False),
    sa.Column('generated_code', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pipelines',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('nl_prompt', sa.Text(), nullable=False),
    sa.Column('plan_json', sa.Text(), nullable=False),
    sa.Column('generated_code', sa.Text(), nullable=True),
    sa.Column('code_mode', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pipelines')
    op.drop_table('pipeline_versions')
    # ### end Alembic commands ###
